### ISSUE TITLE
Tallying and/or closing petitions with 0 signatures 

### ISSUE THREAD

**Issue by andrea-dintino** [DECODEproject/dddc-pilot-contracts#2]
When passing contract 13 a petition with 0 signatures, the count contract (14) fails to produce output, this is the log of Zenroom:

[*] Zenroom v0.8.1 - crypto language restricted VM
 .  Copyright (C) 2017-2019 Dyne.org foundation
 .  reading KEYS from file: credential.json
 .  loaded file (865 bytes)
 .  reading DATA from file: petition.json
 .  loaded file (1424 bytes)
[*] reading Zencode from file: ./src/13-CITIZEN-tally-petition.zencode
 .  loaded file (390 bytes)
 .  using default configuration
 .  loading lua initialisation
[*] Direct Zencode execution
 .  starting execution.
[*] Execution completed.
 .  Zenroom teardown.
[*] Zenroom v0.8.1 - crypto language restricted VM
 .  Copyright (C) 2017-2019 Dyne.org foundation
 .  reading KEYS from file: tally.json
 .  loaded file (1151 bytes)
 .  reading DATA from file: petition.json
 .  loaded file (1424 bytes)
[*] reading Zencode from file: ./src/14-CITIZEN-count-petition.zencode
 .  loaded file (226 bytes)
 .  using default configuration
 .  loading lua initialisation
[*] Direct Zencode execution
 .  starting execution.
[!] ECP point validation returns -2
[!] [string "zencode_schemas"]:26: Octet is not a valid public key (point is not on this curve)
 .  Zenroom teardown.

**Comment by puria** [comment]
Is the petition, already tallied?

**Comment by puria** [comment]
just answer to myself, yes, cause 13 takes the tally as keys ;p

**Comment by jaromil** [comment]
fixed in https://github.com/DECODEproject/zenroom/commit/753658b50f5bfc3efa5aade05bfeef48fe4e7cb8
